package com.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOG.
 */
public class log {

    private Long id;
    private String operType;
    private String operTime;
    private String status;

    public log() {
    }

    public log(Long id) {
        this.id = id;
    }

    public log(Long id, String operType, String operTime, String status) {
        this.id = id;
        this.operType = operType;
        this.operTime = operTime;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOperType() {
        return operType;
    }

    public void setOperType(String operType) {
        this.operType = operType;
    }

    public String getOperTime() {
        return operTime;
    }

    public void setOperTime(String operTime) {
        this.operTime = operTime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
