package com.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VERSION.
 */
public class Version {

    private Long id;
    private String latestVersion;
    private String status;  //1 able //0 disable
    private String createTime;

    public Version() {
    }

    public Version(Long id) {
        this.id = id;
    }

    public Version(Long id, String latestVersion, String status, String createTime) {
        this.id = id;
        this.latestVersion = latestVersion;
        this.status = status;
        this.createTime = createTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLatestVersion() {
        return latestVersion;
    }

    public void setLatestVersion(String latestVersion) {
        this.latestVersion = latestVersion;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

}
